before_install:
- openssl aes-256-cbc -K $encrypted_a1632a6faaa6_key -iv $encrypted_a1632a6faaa6_iv
  -in bar_rsa.enc -out ~/.ssh/bar_rsa -d
- chmod 600 ~/.ssh/bar_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/bar_rsa
- git config --global user.name "Travis Bot"
- git config --global user.email xing-zhi@126.com
- cd ~
- git clone --depth=50  git@github.com:xing-zhi/travis-test.git foo
- cd foo
- git checkout -b master
script:
- cd examples
- git init
- git remote add origin git@github.com:xing-zhi/travis-test.git foo
- git add .
- git commit -m 'Update examples'
- git push -u -f origin master:gh-pages
- rm -rf ~/.ssh
